

services:
  app:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db

    volumes:
      - ./config.yml:/config.yml
      - ./migrations:/migrations
    environment:
      CONFIG_FILE: /config.yml
    command:
      - sh
      - -c
      - |
        sleep 3
        migrate -path /migrations -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable" up
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


