

services:
  app:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy


    volumes:
      - ./config.yml:/app/config.yml
      - ./migrations:/app/migrations
    env_file:
      - .env
    command: >
      sh -c "./wait-for-db.sh db 5432 migrate -path /app/migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable up && ./todo-app --config-file /app/config.yml --listener 1"
      

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:


